#!/bin/sh

TWD=`pwd`

TOP_DIR=`dirname $0`/..
cd "$TOP_DIR"

for i in modules/* ; do
    if [ -d "$i" -a -f "$i/project.clj" ] ; then
        OLDWD=`pwd`
        cd "$i"
        lein clean
        cd "$OLDWD"
    fi
done

lein clean

cd "$TWD"
