#!/bin/sh

TWD=`pwd`

if [ -n "$LEINCMD" ] ; then
    LEIN=$LEINCMD
fi

TOP_DIR=`dirname $0`/..
cd "$TOP_DIR"

for i in modules/* ; do
    if [ -d "$i" -a -f "$i/project.clj" ] ; then
        OLDWD=`pwd`
        cd "$i"
        $LEIN clean
        cd "$OLDWD"
    fi
done

$LEIN clean

cd "$TWD"
