#!/bin/sh

INCANTER_HOME=`dirname $0`/..

CLASSPATH=src:test:config:data:.

for f in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

REPL_JAVA_OPTS="-server -Xmx1G"
SCRIPT_JAVA_OPTS="-server -Xmx1G -XX:+AggressiveOpts"


if [ -z "$1" ]; then
  java $REPL_JAVA_OPTS -Dclojure.compile.path=$CLASSES_DIR -Dincanter.home=$INCANTER_HOME -cp $CLASSPATH jline.ConsoleRunner clojure.main -i script/run.clj -r
else
  scriptname=$1
  java $SCRIPT_JAVA_OPTS -Dclojure.compile.path=$CLASSES_DIR -Dincanter.home=$INCANTER_HOME -cp $CLASSPATH jline.ConsoleRunner clojure.main $scriptname -- $*
fi

