#!/bin/sh

cd modules
for f in core io charts processing mongodb pdf latex ; do
    cd incanter-$f
    lein clean
    lein deps
    jsrc=`find src -name \*.java`
    if [ -n "$jsrc" ] ; then
        lein compile-java
    fi
    lein install
    cd ..
done
cd ..

lein clean
lein deps
lein install

