#!/bin/sh

TWD=`pwd`

LEIN=lein
if [ -n "$LEINCMD" ] ; then
    LEIN=$LEINCMD
fi

TOP_DIR=`dirname $0`/..
cd "$TOP_DIR"

script/clean

cd modules
for i in core io charts mongodb pdf latex excel zoo ; do
    if [ -d "incanter-$i" -a -f "incanter-$i/project.clj" ] ; then
        OLDWD=`pwd`
        cd "incanter-$i"
        $LEIN deploy clojars
        cd "$OLDWD"
    fi
done
cd ..

$LEIN deploy clojars

cd "$TWD"


