#!/bin/sh

TWD=`pwd`

LEIN=lein
if [ -n "$LEINCMD" ] ; then
    LEIN=$LEINCMD
fi

TOP_DIR=`dirname $0`/..
cd "$TOP_DIR"

script/clean

$TOP_DIR/script/run-cmd $LEIN deploy clojars
RES=$?

cd "$TWD"
exit $RES

