#!/bin/sh

TOP_DIR=`dirname $0`/..

JAR_FOUND=0

CP="$TOP_DIR/src:$TOP_DIR/test:$TOP_DIR/data:."
for f in $TOP_DIR/target/incanter-*-standalone.jar; do
    CP="$CP:$f"
    JAR_FOUND=1
done

if [ $JAR_FOUND -eq 0 ] ; then
    echo "run 'lein uberjar in the top-level Incanter directory first"
    exit 1
fi

INCANTER_HOME=$TOP_DIR
export INCANTER_HOME

java -Xmx1G -cp "$CP" incanter.repl -i "$TOP_DIR/script/run.clj" "$@"

