#!/bin/sh

TWD=`pwd`

LEIN=lein
if [ -n "$LEINCMD" ] ; then
    LEIN = $LEINCMD
fi

TOP_DIR=`dirname $0`/..
cd "$TOP_DIR"

cd modules
for i in core io charts mongodb pdf latex excel zoo ; do
    if [ -d "incanter-$i" -a -f "incanter-$i/project.clj" ] ; then
        echo "testing in incanter-$i"
        OLDWD=`pwd`
        cd "incanter-$i"
        $LEIN test
        cd "$OLDWD"
    fi
done

cd "$TWD"

