#!/bin/sh

cd ./modules/incanter-core
lein deps && lein test && lein install

cd ../incanter-io
lein deps && lein test && lein install

cd ../incanter-charts
lein deps && lein test && lein install

cd ../incanter-processing
lein deps && lein test

cd ../incanter-mongodb
lein deps && lein test

cd ../incanter-pdf
lein deps && lein test

cd ../incanter-latex
lein deps && lein test

cd ../incanter-excel
lein deps && lein test
